### ISSUE TITLE
Enable appveyor

### ISSUE THREAD

**Issue by tdegeus** [tdegeus/GooseMPL#4]
```yaml
build: false

branches:
  only:
    - master

platform:
  - x64

image:
  - Visual Studio 2017
  - Visual Studio 2015

environment:
  matrix:
    - MINICONDA: C:\myname-conda

init:
  - "ECHO %MINICONDA%"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" set VCVARPATH="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" set VCARGUMENT=%PLATFORM%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" set VCVARPATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - echo "%VCVARPATH% %VCARGUMENT%"
  - "%VCVARPATH% %VCARGUMENT%"
  - ps: if($env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
  - ps: if($env:Platform -eq "x86"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe' C:\Miniconda.exe; echo "Done"}
  - cmd: C:\Miniconda.exe /S /D=C:\myname-conda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  # Set environment using Conda
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install miktex -c conda-forge
  - conda install python -c conda-forge
  - conda install numpy -c conda-forge
  - conda install matplotlib -c conda-forge
  # Install library
  - pip install .
  - python -c "import GooseMPL; GooseMPL.copy_style()"

build_script:
  # Run tests
  - python docs/examples/goosempl/histogram.py
  - python docs/examples/goosempl/histogram_powerlaw.py
  - python docs/examples/goosempl/patch.py
  - python docs/examples/pyplot/colorbar.py
  - python docs/examples/pyplot/colormap-part.py
  - python docs/examples/pyplot/colormap.py
  - python docs/examples/pyplot/image.py
  - python docs/examples/pyplot/image_subplots.py
  - python docs/examples/pyplot/image_subplots_bottom.py
  - python docs/examples/pyplot/legend_background.py
  - python docs/examples/pyplot/legend_external.py
  - python docs/examples/pyplot/plot-cmap.py
  - python docs/examples/pyplot/plot.py
  - python docs/examples/pyplot/subplot.py
  - python docs/examples/pyplot/tick-formatter.py
  - python docs/examples/pyplot/tick-log.py
  - python docs/examples/pyplot/tick-log_1.py
  - python docs/examples/pyplot/tick-log_2.py
  - python docs/examples/pyplot/tick-position.py
  - python docs/examples/pyplot/tick-rotation-log.py
```
